# Generated by Django 4.2.20 on 2025-09-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_yesnounknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Treated Option',
                'verbose_name_plural': 'Category Treated Options',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='yesnounknown',
            options={'ordering': ['id'], 'verbose_name': 'Yes/No/Unknown Option', 'verbose_name_plural': 'Yes/No/Unknown Options'},
        ),
    ]
