# Generated by Django 4.2.20 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_nanoporesequencingresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='NanoporeSequencingDelayedReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nanopore Sequencing Delayed Reasons Option',
                'verbose_name_plural': 'Nanopore Sequencing Delayed Reasons Options',
                'ordering': ['id'],
            },
        ),
    ]
