# Generated by Django 4.2.20 on 2025-09-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0014_culturemethod_culturemicroscopyresults_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XpertXDRResults2',
            new_name='XpertXDRResultsThree',
        ),
        migrations.RenameModel(
            old_name='XpertXDRResults3',
            new_name='XpertXDRResultsTwo',
        ),
        migrations.AlterModelOptions(
            name='xpertxdrresultsthree',
            options={'ordering': ['id'], 'verbose_name': 'XpertXDR Result Option 3', 'verbose_name_plural': 'PhenXpertXDR Result Options 3'},
        ),
        migrations.AlterModelOptions(
            name='xpertxdrresultstwo',
            options={'ordering': ['id'], 'verbose_name': 'XpertXDR Result Option 2', 'verbose_name_plural': 'PhenXpertXDR Result Options 2'},
        ),
    ]
