# Generated by Django 4.2.20 on 2025-09-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0015_rename_xpertxdrresults2_xpertxdrresultsthree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpertxdrresults',
            options={'ordering': ['id'], 'verbose_name': 'Xpert XDR Result Option', 'verbose_name_plural': 'Xpert XDR Results Options'},
        ),
        migrations.AlterModelOptions(
            name='xpertxdrresultsthree',
            options={'ordering': ['id'], 'verbose_name': 'Xpert XDR Result Option 3', 'verbose_name_plural': 'Xpert XDR Result Options 3'},
        ),
        migrations.AlterModelOptions(
            name='xpertxdrresultstwo',
            options={'ordering': ['id'], 'verbose_name': 'XpertXDR Result Option 2', 'verbose_name_plural': 'Xpert XDR Result Options 2'},
        ),
    ]
