# Generated by Django 4.2.20 on 2025-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='village_street',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
