# Generated by Django 4.2.20 on 2026-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date',)},
            },
        ),
        migrations.CreateModel(
            name='ScreeningDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(db_index=True)),
                ('zone_name', models.CharField(max_length=200)),
                ('site_id', models.IntegerField(db_index=True)),
                ('site_name', models.CharField(max_length=200)),
                ('total_screenings', models.IntegerField(default=0)),
                ('missing_screening_date', models.IntegerField(default=0)),
                ('missing_pid1', models.IntegerField(default=0)),
                ('missing_pid2', models.IntegerField(default=0)),
                ('missing_sex', models.IntegerField(default=0)),
                ('missing_age_dob', models.IntegerField(default=0)),
                ('missing_consent', models.IntegerField(default=0)),
                ('missing_consent_date_when_yes', models.IntegerField(default=0)),
                ('missing_age18years', models.IntegerField(default=0)),
                ('missing_present_symptoms', models.IntegerField(default=0)),
                ('missing_genexpert_confirmation', models.IntegerField(default=0)),
                ('missing_produce_resp_sample', models.IntegerField(default=0)),
                ('missing_unable_understand', models.IntegerField(default=0)),
                ('missing_not_willing', models.IntegerField(default=0)),
                ('missing_enrolled', models.IntegerField(default=0)),
                ('missing_reasons', models.IntegerField(default=0)),
                ('missing_reasons_other', models.IntegerField(default=0)),
                ('duplicate_pids', models.IntegerField(default=0)),
                ('mismatched_pids', models.IntegerField(default=0)),
                ('invalid_length_pids', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_details', to='reports.dataqualitysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'zone_id'], name='reports_scr_snapsho_68c176_idx'), models.Index(fields=['snapshot', 'site_id'], name='reports_scr_snapsho_d1dee7_idx')],
                'unique_together': {('snapshot', 'zone_id', 'site_id')},
            },
        ),
    ]
