# Generated by Django 4.2.20 on 2026-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingformsdqsnapshot',
            name='missing_clinic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingformsdqsnapshot',
            name='missing_diagnosis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingformsdqsnapshot',
            name='missing_enrollment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingformsdqsnapshot',
            name='missing_regimen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingformsdqsnapshot',
            name='missing_zonal',
            field=models.IntegerField(default=0),
        ),
    ]
