# Generated by Django 4.2.20 on 2026-01-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.IntegerField(default=0)),
                ('missing_hiv_status', models.IntegerField(default=0)),
                ('missing_other_diseases', models.IntegerField(default=0)),
                ('missing_sputum_collected', models.IntegerField(default=0)),
                ('missing_sputum_date', models.IntegerField(default=0)),
                ('missing_sputum_reasons', models.IntegerField(default=0)),
                ('missing_diseases_medical', models.IntegerField(default=0)),
                ('missing_diseases_specify', models.IntegerField(default=0)),
                ('missing_dr_ds', models.IntegerField(default=0)),
                ('missing_tb_regimen', models.IntegerField(default=0)),
                ('missing_tb_outcome', models.IntegerField(default=0)),
                ('missing_tb_regimen_specify', models.IntegerField(default=0)),
                ('missing_tb_regimen_specify_8', models.IntegerField(default=0)),
                ('missing_tb_category_specify', models.IntegerField(default=0)),
                ('invalid_ltf_months', models.IntegerField(default=0)),
                ('missing_tx_month_without_unknown', models.IntegerField(default=0)),
                ('invalid_tx_month_with_unknown', models.IntegerField(default=0)),
                ('missing_tx_year_without_unknown', models.IntegerField(default=0)),
                ('invalid_tx_year_with_unknown', models.IntegerField(default=0)),
                ('invalid_unknown_year_dependencies', models.IntegerField(default=0)),
                ('missing_regimen_months_without_unknown', models.IntegerField(default=0)),
                ('invalid_regimen_months_with_unknown', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_details', to='reports.dataqualitysnapshot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.zone')),
            ],
            options={
                'unique_together': {('snapshot', 'zone', 'site')},
            },
        ),
        migrations.CreateModel(
            name='ClinicDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clinics', models.IntegerField(default=0)),
                ('missing_sample_received', models.IntegerField(default=0)),
                ('missing_number_received', models.IntegerField(default=0)),
                ('missing_sample_reason_when_received_2', models.IntegerField(default=0)),
                ('missing_new_reason_when_new_sample_2', models.IntegerField(default=0)),
                ('missing_other_reason_when_sample_reason_96', models.IntegerField(default=0)),
                ('missing_date_sample1_collected', models.IntegerField(default=0)),
                ('missing_date_sample1_received', models.IntegerField(default=0)),
                ('missing_appearance_sample1', models.IntegerField(default=0)),
                ('missing_sample1_volume', models.IntegerField(default=0)),
                ('missing_date_sample2_collected', models.IntegerField(default=0)),
                ('missing_date_sample2_received', models.IntegerField(default=0)),
                ('missing_appearance_sample2', models.IntegerField(default=0)),
                ('missing_sample2_volume', models.IntegerField(default=0)),
                ('missing_afb_microscopy_conducted', models.IntegerField(default=0)),
                ('missing_afb_a_date', models.IntegerField(default=0)),
                ('missing_technique_a', models.IntegerField(default=0)),
                ('missing_afb_a_results', models.IntegerField(default=0)),
                ('missing_afb_b_date', models.IntegerField(default=0)),
                ('missing_technique_b', models.IntegerField(default=0)),
                ('missing_afb_b_results', models.IntegerField(default=0)),
                ('missing_xpert_mtb_rif_conducted', models.IntegerField(default=0)),
                ('missing_xpert_date', models.IntegerField(default=0)),
                ('missing_xpert_mtb', models.IntegerField(default=0)),
                ('missing_error_code', models.IntegerField(default=0)),
                ('missing_xpert_rif', models.IntegerField(default=0)),
                ('missing_ct_value', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_details', to='reports.dataqualitysnapshot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'zone'], name='reports_cli_snapsho_c09b06_idx'), models.Index(fields=['snapshot', 'site'], name='reports_cli_snapsho_2d9a2c_idx')],
                'unique_together': {('snapshot', 'zone', 'site')},
            },
        ),
    ]
