# Generated by Django 4.2.20 on 2026-01-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('reports', '0002_enrollmentdqsnapshot_clinicdqsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diagnoses', models.IntegerField(default=0)),
                ('missing_tb_diagnosis', models.IntegerField(default=0)),
                ('missing_tb_diagnosis_date', models.IntegerField(default=0)),
                ('missing_tb_diagnosis_made', models.IntegerField(default=0)),
                ('missing_tb_treatment', models.IntegerField(default=0)),
                ('missing_diagnosis_made_other', models.IntegerField(default=0)),
                ('missing_tb_diagnosed_clinically', models.IntegerField(default=0)),
                ('missing_tb_clinically_other', models.IntegerField(default=0)),
                ('missing_bacteriological_diagnosis', models.IntegerField(default=0)),
                ('missing_clinician_received_date', models.IntegerField(default=0)),
                ('missing_tb_other_diagnosis', models.IntegerField(default=0)),
                ('missing_tb_diagnosis_made2', models.IntegerField(default=0)),
                ('missing_tb_other_specify', models.IntegerField(default=0)),
                ('missing_tb_treatment_date', models.IntegerField(default=0)),
                ('missing_tb_register_number', models.IntegerField(default=0)),
                ('duplicate_tb_register_number', models.IntegerField(default=0)),
                ('missing_tb_regimen', models.IntegerField(default=0)),
                ('missing_regimen_changed', models.IntegerField(default=0)),
                ('missing_tb_facility', models.IntegerField(default=0)),
                ('missing_tb_reason', models.IntegerField(default=0)),
                ('pending_tb_outcome', models.IntegerField(default=0)),
                ('pending_tb_outcome_date', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_details', to='reports.dataqualitysnapshot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'zone'], name='reports_dia_snapsho_019757_idx'), models.Index(fields=['snapshot', 'site'], name='reports_dia_snapsho_dc272e_idx')],
                'unique_together': {('snapshot', 'zone', 'site')},
            },
        ),
    ]
