# Generated by Django 4.2.20 on 2026-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_missingformsdqsnapshot_missing_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratorydqsnapshot',
            name='missing_lpa',
            field=models.IntegerField(default=0),
        ),
    ]
