# Generated by Django 4.2.20 on 2026-01-31 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_diagnosisdqsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(db_index=True)),
                ('zone_name', models.CharField(max_length=200)),
                ('site_id', models.IntegerField(db_index=True)),
                ('site_name', models.CharField(max_length=200)),
                ('total_regimens', models.IntegerField(default=0)),
                ('missing_date', models.IntegerField(default=0)),
                ('missing_drug', models.IntegerField(default=0)),
                ('missing_changes', models.IntegerField(default=0)),
                ('missing_reason', models.IntegerField(default=0)),
                ('missing_specify_when_other', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimen_details', to='reports.dataqualitysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'zone_id'], name='reports_reg_snapsho_261636_idx'), models.Index(fields=['snapshot', 'site_id'], name='reports_reg_snapsho_7e5bff_idx')],
                'unique_together': {('snapshot', 'zone_id', 'site_id')},
            },
        ),
    ]
