# Generated by Django 4.2.20 on 2026-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_zonallaboratorydqsnapshot_missing_lpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratorydqsnapshot',
            name='missing_nanopore_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zonallaboratorydqsnapshot',
            name='missing_sequencing_results',
            field=models.IntegerField(default=0),
        ),
    ]
