# Generated by Django 4.2.20 on 2026-01-31 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_regimendqsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonalLaboratoryDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(db_index=True)),
                ('zone_name', models.CharField(max_length=200)),
                ('site_id', models.IntegerField(db_index=True)),
                ('site_name', models.CharField(max_length=200)),
                ('total_records', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('missing_date_sputum_received', models.IntegerField(default=0)),
                ('missing_unique_lab_no', models.IntegerField(default=0)),
                ('duplicate_unique_lab_no', models.IntegerField(default=0)),
                ('missing_sample_volume', models.IntegerField(default=0)),
                ('missing_appearance', models.IntegerField(default=0)),
                ('missing_culture_performed', models.IntegerField(default=0)),
                ('missing_culture_method', models.IntegerField(default=0)),
                ('missing_microscopy_type', models.IntegerField(default=0)),
                ('missing_microscopy_date', models.IntegerField(default=0)),
                ('missing_microscopy_results', models.IntegerField(default=0)),
                ('missing_lj_inoculation_date', models.IntegerField(default=0)),
                ('missing_lj_results_date', models.IntegerField(default=0)),
                ('missing_lj_results', models.IntegerField(default=0)),
                ('missing_mgit_inoculation_date', models.IntegerField(default=0)),
                ('missing_mgit_results_date', models.IntegerField(default=0)),
                ('missing_mgit_results', models.IntegerField(default=0)),
                ('missing_culture_isolate', models.IntegerField(default=0)),
                ('missing_isolate_date', models.IntegerField(default=0)),
                ('missing_phenotypic_performed', models.IntegerField(default=0)),
                ('missing_phenotypic_date_performed', models.IntegerField(default=0)),
                ('missing_phenotypic_date_results', models.IntegerField(default=0)),
                ('missing_phenotypic_dst_results', models.IntegerField(default=0)),
                ('missing_xpert_xdr_performed', models.IntegerField(default=0)),
                ('missing_xpert_xdr_date_performed', models.IntegerField(default=0)),
                ('missing_xpert_xdr_results', models.IntegerField(default=0)),
                ('missing_first_line_lpa_date', models.IntegerField(default=0)),
                ('missing_first_line_drugs', models.IntegerField(default=0)),
                ('missing_lpa1_mtb', models.IntegerField(default=0)),
                ('missing_lpa1_rif', models.IntegerField(default=0)),
                ('missing_lpa1_inh', models.IntegerField(default=0)),
                ('missing_second_line_lpa_date', models.IntegerField(default=0)),
                ('missing_second_line_drugs', models.IntegerField(default=0)),
                ('missing_lpa2_mtb', models.IntegerField(default=0)),
                ('missing_lpa2_rfluoroquinolones', models.IntegerField(default=0)),
                ('missing_lpa2_aminoglycosides', models.IntegerField(default=0)),
                ('missing_lpa2_kanamycin', models.IntegerField(default=0)),
                ('missing_nanopore_sequencing_date', models.IntegerField(default=0)),
                ('missing_nanopore_results', models.IntegerField(default=0)),
                ('missing_epi_to_me', models.IntegerField(default=0)),
                ('missing_sequencing_delayed', models.IntegerField(default=0)),
                ('missing_sequencing_delayed_days', models.IntegerField(default=0)),
                ('missing_sequencing_delayed_reasons', models.IntegerField(default=0)),
                ('missing_sequencing_delayed_others', models.IntegerField(default=0)),
                ('missing_epi_to_me_date', models.IntegerField(default=0)),
                ('missing_epi_to_me_version', models.IntegerField(default=0)),
                ('missing_nanopore_drug_results', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_lab_details', to='reports.dataqualitysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'zone_id'], name='reports_zon_snapsho_26536c_idx'), models.Index(fields=['snapshot', 'site_id'], name='reports_zon_snapsho_9ac04d_idx')],
                'unique_together': {('snapshot', 'zone_id', 'site_id')},
            },
        ),
    ]
