# Generated by Django 4.2.20 on 2026-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_zonallaboratorydqsnapshot_missing_nanopore_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratorydqsnapshot',
            name='missing_isolate_unique_lab_no',
            field=models.IntegerField(default=0),
        ),
    ]
