# Generated by Django 4.2.20 on 2026-01-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('nanopore', '0019_remove_zonallaboratory_sequencing_delayed_reasons_and_more'),
        ('reports', '0005_zonallaboratorydqsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingFormsDQSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_enrollment', models.BooleanField(default=False)),
                ('missing_clinic', models.BooleanField(default=False)),
                ('missing_diagnosis', models.BooleanField(default=False)),
                ('missing_regimen', models.BooleanField(default=False)),
                ('missing_zonal', models.BooleanField(default=False)),
                ('total_issues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopore.screening')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.site')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dataqualitysnapshot')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.zone')),
            ],
            options={
                'verbose_name': 'Missing Forms Data Quality Snapshot',
                'verbose_name_plural': 'Missing Forms Data Quality Snapshots',
            },
        ),
    ]
