# Generated by Django 4.2.20 on 2025-09-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0004_alter_screening_age18years_alter_screening_consent_and_more'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YesNo',
        ),
        migrations.DeleteModel(
            name='YesNoNA',
        ),
    ]
