# Generated by Django 4.2.20 on 2025-09-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_delete_yesno_delete_yesnona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['id'], 'verbose_name': 'Competence', 'verbose_name_plural': 'Competences'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['id'], 'verbose_name': 'Disease Option', 'verbose_name_plural': 'Disease Options'},
        ),
    ]
