# Generated by Django 4.2.20 on 2025-09-03 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('demographic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('pid1', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='This field must be exactly 3 digits.', regex='^\\d{3}$')])),
                ('pid2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='This field must be exactly 3 digits.', regex='^\\d{3}$')])),
                ('pid', models.CharField(editable=False, max_length=255, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('eligible', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_consent', to='clinical.yesno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings_created', to=settings.AUTH_USER_MODEL)),
                ('enrolled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_enrolled', to='clinical.yesno')),
                ('genexpert_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_genexpert_confirmation', to='clinical.yesno')),
                ('not_willing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_not_willing', to='clinical.yesno')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demographic.sex')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.site')),
                ('unable_understand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_unable_understand', to='clinical.yesno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['screening_date', 'pid'],
            },
        ),
        migrations.CreateModel(
            name='ZonalLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('test_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_labs_created', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_laboratory', to='nanopore.screening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_labs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='nanopore.screening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['screening'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_created', to=settings.AUTH_USER_MODEL)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='nanopore.screening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('test_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_labs_created', to=settings.AUTH_USER_MODEL)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_laboratory', to='nanopore.screening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_labs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
