# Generated by Django 4.2.20 on 2025-09-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniclaboratory',
            options={'ordering': ['-sample_received']},
        ),
        migrations.RemoveField(
            model_name='cliniclaboratory',
            name='result',
        ),
        migrations.RemoveField(
            model_name='cliniclaboratory',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='cliniclaboratory',
            name='test_name',
        ),
    ]
