# Generated by Django 4.2.20 on 2025-09-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_diseasesmedicalconditions'),
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='cough2weeks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_cough2weeks', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='coughing_blood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_coughing_blood', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='history_tb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_history_tb', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='neck_lymph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_neck_lymph', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='night_sweats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_night_sweats', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='poor_weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_poor_weight', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='unexplained_fever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_unexplained_fever', to='options.yesno'),
            preserve_default=False,
        ),
    ]
