# Generated by Django 4.2.20 on 2025-09-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='age18years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_age18years', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_consent', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_enrolled', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='genexpert_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_genexpert_confirmation', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='not_willing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_not_willing', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='present_symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_present_symptoms', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='produce_resp_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_produce_resp_sample', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_enrolled_reasons', to='options.enrolledreason'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='unable_understand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_unable_understand', to='options.yesno'),
        ),
    ]
