# Generated by Django 4.2.20 on 2025-09-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_appearance', to='options.sampleappearance'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='date_sputum_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sample_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
