# Generated by Django 4.2.20 on 2025-09-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='genexpert_confirmation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='screening_genexpert_confirmation', to='clinical.yesno'),
            preserve_default=False,
        ),
    ]
