# Generated by Django 4.2.20 on 2025-09-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_amikacin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_bedaquiline',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_capreomycin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_clofazimine',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_delamanid',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_ethambutol',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_ethionamide',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_isoniazid',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_kanamycin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_levofloxacin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_linezolid',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_moxifloxacin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_pretomanid',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_pyrazinamide',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_rifampicin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nano_streptomycin',
        ),
    ]
