# Generated by Django 4.2.20 on 2025-09-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='tx_previous',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_tx_previous', to='options.yesnounknown'),
            preserve_default=False,
        ),
    ]
