# Generated by Django 4.2.20 on 2025-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0002_screening_genexpert_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='pid',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
