# Generated by Django 4.2.20 on 2025-09-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0002_alter_enrollment_tx_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='number_received',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_lab_number_received', to='options.samplenumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='sample_received',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_lab_sample_received', to='options.yesno'),
            preserve_default=False,
        ),
    ]
