# Generated by Django 4.2.20 on 2025-09-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0002_alter_cliniclaboratory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonallaboratory',
            options={'ordering': ['-date_sputum_received']},
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='result',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='test_name',
        ),
    ]
