# Generated by Django 4.2.20 on 2025-09-06 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0002_alter_enrollment_cough2weeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_information_collected',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
