# Generated by Django 4.2.20 on 2025-09-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0002_zonallaboratory_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_method',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_culture_method', to='options.culturemethod'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_performed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_inoculation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lj_results', to='options.ljcultureresult'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_inoculation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_mgit_results', to='options.mgitcultureresult'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_microscopy_results', to='options.culturemicroscopyresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_microscopy_type', to='options.microscopytype'),
        ),
    ]
