# Generated by Django 4.2.20 on 2025-09-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demographic', '0001_initial'),
        ('nanopore', '0002_alter_screening_age18years_alter_screening_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings_sex', to='demographic.sex'),
        ),
    ]
