# Generated by Django 4.2.20 on 2025-09-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0002_remove_zonallaboratory_nano_amikacin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_amikacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_amikacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_bedaquiline',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_bedaquiline', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_capreomycin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_capreomycin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_clofazimine',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_clofazimine', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_delamanid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_delamanid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_ethambutol',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethambutol', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_ethionamide',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethionamide', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_isoniazid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_isoniazid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_kanamycin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_kanamycin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_levofloxacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_levofloxacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_linezolid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_linezolid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_moxifloxacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_moxifloxacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_pretomanid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pretomanid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_pyrazinamide',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pyrazinamide', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_rifampicin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_rifampicin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_streptomycin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_streptomycin', to='options.nanoporeresults'),
        ),
    ]
