# Generated by Django 4.2.20 on 2025-09-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0003_alter_zonallaboratory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-tb_diagnosis_date']},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_date',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_name',
        ),
    ]
