# Generated by Django 4.2.20 on 2025-09-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0002_alter_enrolledreason_table'),
        ('clinical', '0001_initial'),
        ('nanopore', '0003_alter_diagnosis_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='age18years',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='screening_age18years', to='clinical.yesno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='present_symptoms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='screening_present_symptoms', to='clinical.yesno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='produce_resp_sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='screening_produce_resp_sample', to='clinical.yesno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_enrolled_reasons', to='reasons.enrolledreason'),
        ),
        migrations.AddField(
            model_name='screening',
            name='reasons_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='genexpert_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_genexpert_confirmation', to='clinical.yesno'),
        ),
    ]
