# Generated by Django 4.2.20 on 2025-09-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0003_zonallaboratory_nano_amikacin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='age18years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_age18years', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_consent', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_enrolled', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='genexpert_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_genexpert_confirmation', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='not_willing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_not_willing', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='present_symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_present_symptoms', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='produce_resp_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_produce_resp_sample', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='unable_understand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_unable_understand', to='options.yesno'),
        ),
    ]
