# Generated by Django 4.2.20 on 2025-09-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0003_alter_cliniclaboratory_number_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='afb_microscopy_conducted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_lab_afb_microscopy_conducted', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='xpert_mtb_rif_conducted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_lab_xpert_mtb_rif_conducted', to='options.yesno'),
            preserve_default=False,
        ),
    ]
