# Generated by Django 4.2.20 on 2025-09-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0003_zonallaboratory_culture_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_isolate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_isolate', to='options.yesnona'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isolate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_date_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_date_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_phenotypic_date_results', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_phenotypic_performed', to='options.yesno'),
        ),
    ]
