# Generated by Django 4.2.20 on 2025-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0003_alter_screening_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
