# Generated by Django 4.2.20 on 2025-09-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_diseasesmedicalconditions'),
        ('nanopore', '0003_alter_enrollment_date_information_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='history_tb',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='diseases_medical',
            field=models.ManyToManyField(blank=True, related_name='enrollment_diseases_medical', to='options.diseasesmedicalconditions'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='diseases_specify',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='dr_ds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_dr_ds', to='options.drdstb'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='hiv_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_hiv_status', to='options.positivenegativeunknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ltf_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ltf_months_unknown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_ltf_months_unknown', to='options.monthunknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='other_diseases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_other_diseases', to='options.yesnounknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='regimen_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='regimen_months_unknown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_regimen_months_unknown', to='options.monthunknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sputum_collected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_sputum_collected', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sputum_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sputum_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tb_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tb_category', to='options.categorytreated'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tb_category_specify',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tb_otcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tb_outcome', to='options.treatmentoutcome'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tb_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tb_regimen', to='options.treatmentregimen'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tb_regimen_specify',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tx_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tx_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tx_previous', to='options.yesnounknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tx_unknown_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tx_unknown_month', to='options.monthunknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tx_unknown_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tx_unknown_year', to='options.yearunknown'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tx_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
