# Generated by Django 4.2.20 on 2025-09-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0004_alter_screening_age_alter_screening_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='eligible_again',
            field=models.BooleanField(default=False),
        ),
    ]
