# Generated by Django 4.2.20 on 2025-09-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0004_alter_screening_age18years_alter_screening_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='epi_to_me',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='epi_to_me_version',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='first_line_drugs',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='first_line_lpa',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='first_line_lpa_date',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa1_inh',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa1_mtb',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa1_rif',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa2_aminoglycosides',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa2_kanamycin',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa2_mtb',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa2_rfluoroquinolones',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='nanopore_done',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='second_line_drugs',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='second_line_lpa',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='second_line_lpa_date',
        ),
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='sequencing_results',
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='amikacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_amikacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='bedaquiline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_bedaquiline_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='cilastatin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cilastatin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='clofazimine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_clofazimine_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='cycloserine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cycloserine_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='delamanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_delamanid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='ethambutol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethambutol_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='ethionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethionamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='imipenem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_imipenem_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='isoniazid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_isoniazid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='levofloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_levofloxacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='linezolid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_linezolid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='meropenem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_meropenem_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='moxifloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_moxifloxacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_amikacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_amikacin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_bedaquiline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_bedaquiline', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_capreomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_capreomycin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_clofazimine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_clofazimine', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_delamanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_delamanid', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_ethambutol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethambutol', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_ethionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethionamide', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_isoniazid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_isoniazid', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_kanamycin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_levofloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_levofloxacin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_linezolid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_linezolid', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_moxifloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_moxifloxacin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_pretomanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pretomanid', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_pyrazinamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pyrazinamide', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_rifampicin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_rifampicin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nano_streptomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_streptomycin', to='options.nanoporeresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='para_aminosalicylic_acid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_para_aminosalicylic_acid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='prothionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_prothionamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='pyrazinamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_pyrazinamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='rifampicin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_rifampicin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='streptomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_streptomycin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='terizidone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_terizidone_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_amikacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_amikacin_xpert_xdr', to='options.xpertxdrresultsthree'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_capreomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_capreomycin_xpert_xdr', to='options.xpertxdrresultsthree'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_ethionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethionamide_xpert_xdr', to='options.xpertxdrresultstwo'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_fluoroquinolones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_fluoroquinolones_xpert_xdr', to='options.xpertxdrresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_isoniazid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_isoniazid_xpert_xdr', to='options.xpertxdrresults'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='xpert_xdr_kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_kanamycin_xpert_xdr', to='options.xpertxdrresultsthree'),
        ),
    ]
