# Generated by Django 4.2.20 on 2025-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0004_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='pid1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pid2',
            field=models.CharField(max_length=3),
        ),
    ]
