# Generated by Django 4.2.20 on 2025-09-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_diseasesmedicalconditions'),
        ('nanopore', '0004_remove_enrollment_history_tb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclaboratory',
            name='date_sample1_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='sample_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_sample_received', to='options.yesno'),
        ),
    ]
