# Generated by Django 4.2.20 on 2025-09-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0004_zonallaboratory_culture_isolate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='amikacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_amikacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='bedaquiline',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_bedaquiline_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='cilastatin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cilastatin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='clofazimine',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_clofazimine_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='cycloserine',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cycloserine_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='delamanid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_delamanid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='ethambutol',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethambutol_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='ethionamide',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethionamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='imipenem',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_imipenem_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isoniazid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_isoniazid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='levofloxacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_levofloxacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='linezolid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_linezolid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='meropenem',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_meropenem_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='moxifloxacin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_moxifloxacin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='para_aminosalicylic_acid',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_para_aminosalicylic_acid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='prothionamide',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_prothionamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='pyrazinamide',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_pyrazinamide_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='rifampicin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_rifampicin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='streptomycin',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_streptomycin_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='terizidone',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_terizidone_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
    ]
