# Generated by Django 4.2.20 on 2025-09-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('nanopore', '0004_screening_age18years_screening_present_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='enrolled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='screening_enrolled', to='clinical.yesno'),
            preserve_default=False,
        ),
    ]
