# Generated by Django 4.2.20 on 2025-09-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0004_alter_cliniclaboratory_afb_microscopy_conducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='xpert_mtb_rif_conducted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_xpert_mtb_rif_conducted', to='options.yesno'),
        ),
    ]
