# Generated by Django 4.2.20 on 2025-09-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0005_screening_eligible_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='eligible_again',
        ),
    ]
