# Generated by Django 4.2.20 on 2025-09-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('nanopore', '0005_alter_screening_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='present_symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_present_symptoms', to='clinical.yesno'),
        ),
    ]
