# Generated by Django 4.2.20 on 2025-09-09 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0005_alter_screening_pid1_alter_screening_pid2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='pid1',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='This field must be exactly 3 digits.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pid2',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='This field must be exactly 3 digits.', regex='^\\d{3}$')]),
        ),
    ]
