# Generated by Django 4.2.20 on 2025-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0005_cliniclaboratory_date_sample1_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclaboratory',
            name='sample_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
