# Generated by Django 4.2.20 on 2025-09-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0005_remove_zonallaboratory_epi_to_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='epi_to_me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_epi_to_me', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='epi_to_me_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_drugs',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_first_line_drugs', to='options.firstlinedrugs'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_lpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_first_line_lpa', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_lpa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_inh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_inh', to='options.inhresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_mtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_mtb', to='options.mtbresultslpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_rif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_rif', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_aminoglycosides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_aminoglycosides', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_kanamycin', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_mtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_mtb', to='options.mtbresultslpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_rfluoroquinolones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_rfluoroquinolones', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nanopore_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nanopore_done', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_drugs',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_second_line_drugs', to='options.secondlinedrugs'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_lpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_second_line_lpa', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_lpa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_sequencing_results', to='options.yesno'),
        ),
    ]
