# Generated by Django 4.2.20 on 2025-09-14 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0006_alter_cliniclaboratory_xpert_mtb_rif_conducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonallaboratory',
            name='appearance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_appearance', to='options.sampleappearance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='culture_method',
            field=models.ManyToManyField(related_name='zonal_laboratory_culture_method', to='options.culturemethod'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='culture_performed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_culture_performed', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='date_sputum_received',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='epi_to_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_epi_to_me', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='epi_to_me_version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nanopore_done',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_nanopore_done', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='sample_volume',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='sequencing_results',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_sequencing_results', to='options.yesno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
