# Generated by Django 4.2.20 on 2025-09-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0011_samplenumber'),
        ('nanopore', '0006_cliniclaboratory_sample_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='sample_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_sample_reason', to='options.samplereason'),
        ),
    ]
