# Generated by Django 4.2.20 on 2025-09-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0006_alter_screening_pid1_alter_screening_pid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosis_made2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_other_diagnosis_made', to='options.tbotherdiagnosismade'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_other_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_other_diagnosis', to='options.tbotherdiagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_other_specify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
