# Generated by Django 4.2.20 on 2025-09-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0007_diagnosis_tb_diagnosis_made2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='pid',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
