# Generated by Django 4.2.20 on 2025-09-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0012_afbmicroscopyresult_afbtechnique_nospcresult_and_more'),
        ('nanopore', '0007_alter_cliniclaboratory_sample_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclaboratory',
            name='afb_a_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='afb_a_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_afb_a_results', to='options.afbmicroscopyresult'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='afb_b_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='afb_b_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_afb_b_results', to='options.afbmicroscopyresult'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='afb_microscopy_conducted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_afb_microscopy_conducted', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='appearance_sample1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_appearance_sample1', to='options.sampleappearance'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='appearance_sample2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_appearance_sample2', to='options.sampleappearance'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='ct_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_ct_na', to='options.nospcresult'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='ct_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='date_sample1_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='date_sample2_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='date_sample2_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='new_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='new_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_new_sample', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='number_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_number_received', to='options.samplenumber'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='other_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='sample1_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='sample2_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='technique_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_technique_a', to='options.afbtechnique'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='technique_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_technique_b', to='options.afbtechnique'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='xpert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='xpert_mtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_xpert_mtb', to='options.xpertmtb'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='xpert_mtb_rif_conducted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_xpert_mtb_rif_conducted', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='cliniclaboratory',
            name='xpert_rif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_xpert_rif', to='options.xpertrif'),
        ),
    ]
