# Generated by Django 4.2.20 on 2025-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0007_alter_zonallaboratory_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(max_length=100),
        ),
    ]
