# Generated by Django 4.2.20 on 2025-09-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0013_diagnosedclinically_diagnosisbacteriological_and_more'),
        ('nanopore', '0008_cliniclaboratory_afb_a_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='bacteriological_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bacteriological_diagnosis', to='options.diagnosisbacteriological'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='clinician_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_made_other',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='regimen_changed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regimen_changed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_clinically_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosed_clinically',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_diagnosed_clinically', to='options.diagnosedclinically'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_diagnosis', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosis_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_diagnosis_made', to='options.tbdiagnosismade'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_facility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_outcome2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_outcome2', to='options.tbtreatmentoutcome'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_outcome2_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_regimen', to='options.regimenprescribed'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_regimen_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_register_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_treatment', to='options.tbtreatmentstarted'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
