# Generated by Django 4.2.20 on 2025-09-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0008_alter_screening_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='tb_diagnosed_clinically',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tb_diagnosed_clinically',
            field=models.ManyToManyField(blank=True, null=True, related_name='tb_diagnosed_clinically', to='options.diagnosedclinically'),
        ),
    ]
