# Generated by Django 4.2.20 on 2025-09-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0008_alter_zonallaboratory_unique_lab_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonallaboratory',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_appearance', to='options.sampleappearance'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='culture_method',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_culture_method', to='options.culturemethod'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='culture_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_performed', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='date_sputum_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='epi_to_me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_epi_to_me', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='epi_to_me_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nanopore_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nanopore_done', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='sample_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='sequencing_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_sequencing_results', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
