# Generated by Django 4.2.20 on 2025-09-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0009_alter_zonallaboratory_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonallaboratory',
            name='culture_performed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zonal_laboratory_culture_performed', to='options.yesno'),
            preserve_default=False,
        ),
    ]
