# Generated by Django 4.2.20 on 2025-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0009_remove_diagnosis_tb_diagnosed_clinically_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='tb_diagnosed_clinically',
            field=models.ManyToManyField(blank=True, related_name='tb_diagnosed_clinically', to='options.diagnosedclinically'),
        ),
    ]
