# Generated by Django 4.2.20 on 2025-09-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0016_alter_xpertxdrresults_options_and_more'),
        ('nanopore', '0009_diagnosis_bacteriological_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='amikacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_amikacin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='amikacin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_amikacin2', to='options.xpertxdrresultsthree'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_appearance', to='options.sampleappearance'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='bedaquiline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_bedaquiline', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='capreomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_capreomycin', to='options.xpertxdrresultsthree'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='cilastatin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cilastatin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='clofazimine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_clofazimine', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_isolate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_isolate', to='options.yesnona'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_method', to='options.culturemethod'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='culture_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_performed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='cycloserine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_cycloserine', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='date_sputum_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='delamanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_delamanid', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='epi_to_me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_epi_to_me', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='epi_to_me_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='ethambutol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethambutol', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='ethionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethionamide', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='ethionamide2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_ethionamide2', to='options.xpertxdrresultstwo'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_drugs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_first_line_drugs', to='options.firstlinedrugs'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_lpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_first_line_lpa', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_lpa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='fluoroquinolones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_fluoroquinolones', to='options.xpertxdrresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='imipenem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_imipenem', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isolate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isoniazid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_isoniazid', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isoniazid2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_isoniazid2', to='options.xpertxdrresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_kanamycin', to='options.xpertxdrresultsthree'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='levofloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_levofloxacin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='linezolid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_linezolid', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_inoculation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lj_results', to='options.ljcultureresult'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lj_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_inh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_inh', to='options.inhresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_mtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_mtb', to='options.mtbresultslpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_rif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa1_rif', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_aminoglycosides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_aminoglycosides', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_kanamycin', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_mtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_mtb', to='options.mtbresultslpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa2_rfluoroquinolones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa2_rfluoroquinolones', to='options.rifresultlpa'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='meropenem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_meropenem', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_inoculation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_mgit_results', to='options.mgitcultureresult'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='mgit_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_microscopy_results', to='options.culturemicroscopyresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='microscopy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_culture_microscopy_type', to='options.microscopytype'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='moxifloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_moxifloxacin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_amikacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_amikacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_bedaquiline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_bedaquiline', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_capreomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_capreomycin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_clofazimine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_clofazimine', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_delamanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_delamanid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_ethambutol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethambutol', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_ethionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_ethionamide', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_isoniazid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_isoniazid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_kanamycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_kanamycin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_levofloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_levofloxacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_linezolid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_linezolid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_moxifloxacin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_moxifloxacin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_pretomanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pretomanid', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_pyrazinamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_pyrazinamide', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_rifampicin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_rifampicin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nano_streptomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nano_streptomycin', to='options.nanoporeresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nanopore_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nanopore_done', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='para_aminosalicylic_acid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_para_aminosalicylic_acid', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_date_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_date_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_phenotypic_date_results', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='phenotypic_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_phenotypic_performed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='prothionamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_prothionamide', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='pyrazinamide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_pyrazinamide', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='rifampicin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_rifampicin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sample_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_drugs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_second_line_drugs', to='options.secondlinedrugs'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_lpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_second_line_lpa', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_lpa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_sequencing_results', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='streptomycin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_streptomycin', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='terizidone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_terizidone', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='xpert_xdr_date_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='xpert_xdr_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_xpert_xdr_performed', to='options.yesno'),
        ),
    ]
