# Generated by Django 4.2.20 on 2025-09-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0010_alter_zonallaboratory_culture_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='history_tb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_history_tb', to='options.yesno'),
        ),
    ]
