# Generated by Django 4.2.20 on 2025-09-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0011_regimenchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimenchanges',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimen_changes', to='nanopore.screening'),
        ),
    ]
