# Generated by Django 4.2.20 on 2025-09-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0012_alter_enrollment_history_tb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regimenchanges',
            options={'ordering': ['-date'], 'verbose_name': 'Regimen Change', 'verbose_name_plural': 'Regimen Changes'},
        ),
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='afb_microscopy_conducted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_afb_microscopy_conducted', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='cliniclaboratory',
            name='xpert_mtb_rif_conducted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_xpert_mtb_rif_conducted', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='regimenchanges',
            name='changes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regimen_changes', to='options.regimentypeofchange'),
        ),
        migrations.AlterField(
            model_name='regimenchanges',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regimenchanges',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regimen_reasons', to='options.regimenreasonforchange'),
        ),
    ]
