# Generated by Django 4.2.20 on 2025-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0012_alter_regimenchanges_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='lpa1_inh',
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa1_inh',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_lpa1_inh', to='options.inhresultlpa'),
        ),
    ]
