# Generated by Django 4.2.20 on 2025-09-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0013_remove_zonallaboratory_lpa1_inh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='history_tb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_history_tb', to='options.yesno'),
            preserve_default=False,
        ),
    ]
