# Generated by Django 4.2.20 on 2025-09-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tbotherdiagnosis_tbotherdiagnosismade'),
        ('nanopore', '0014_alter_cliniclaboratory_afb_microscopy_conducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='tb_diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tb_diagnosis', to='options.yesno'),
            preserve_default=False,
        ),
    ]
