# Generated by Django 4.2.20 on 2025-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0015_alter_diagnosis_tb_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonallaboratory',
            name='unique_lab_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
