# Generated by Django 4.2.20 on 2025-10-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_nanoporesequencingresults'),
        ('nanopore', '0016_alter_zonallaboratory_unique_lab_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='epi_to_me_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nanopore_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nanopore_results', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='nanopore_sequencing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
