# Generated by Django 4.2.20 on 2025-10-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0017_zonallaboratory_epi_to_me_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_delayed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_sequencing_delayed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_delayed_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_delayed_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_delayed_reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_sequencing_delayed_reasons', to='options.nanoporesequencingdelayedreasons'),
        ),
        migrations.AlterField(
            model_name='zonallaboratory',
            name='nanopore_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_nanopore_results', to='options.nanoporesequencingresults'),
        ),
    ]
