# Generated by Django 4.2.20 on 2025-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0018_zonallaboratory_sequencing_delayed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='sequencing_delayed_reasons',
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='sequencing_delayed_reasons',
            field=models.ManyToManyField(blank=True, related_name='zonal_laboratory_sequencing_delayed_reasons', to='options.nanoporesequencingdelayedreasons'),
        ),
    ]
