# Generated by Django 4.2.20 on 2026-02-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0019_remove_zonallaboratory_sequencing_delayed_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='lpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_lpa', to='options.yesno'),
        ),
    ]
