# Generated by Django 4.2.20 on 2026-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0021_edcstbliszonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='unique_lab_no',
            field=models.CharField(max_length=100),
        ),
    ]
