# Generated by Django 4.2.20 on 2026-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0022_alter_edcstbliszonal_unique_lab_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
