# Generated by Django 4.2.20 on 2026-02-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0023_alter_edcstbliszonal_unique_lab_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='unique_lab_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
