# Generated by Django 4.2.20 on 2026-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0024_alter_edcstbliszonal_unique_lab_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstbliszonal',
            name='isolate_unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='isolate_unique_lab_no',
            field=models.CharField(blank=True, help_text='Lab number, must be unique if present for isolate dst', max_length=100, null=True, unique=True),
        ),
    ]
