# Generated by Django 4.2.20 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0025_edcstbliszonal_isolate_unique_lab_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edcstbliszonal',
            name='isolate_unique_lab_no',
        ),
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='unique_lab_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
