# Generated by Django 4.2.20 on 2026-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0026_remove_edcstbliszonal_isolate_unique_lab_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonallaboratory',
            name='isolate_unique_lab_no',
        ),
        migrations.AddField(
            model_name='edcstbliszonal',
            name='isolate_unique_lab_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='unique_lab_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
