# Generated by Django 4.2.20 on 2026-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0027_remove_zonallaboratory_isolate_unique_lab_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='isolate_unique_lab_no',
            field=models.CharField(blank=True, help_text='Lab number, must be unique if present for isolate dst', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_dst_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_dst_results_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
