# Generated by Django 4.2.20 on 2026-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0028_zonallaboratory_isolate_unique_lab_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstbliszonal',
            name='first_line_dst_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edcstbliszonal',
            name='first_line_dst_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edcstbliszonal',
            name='second_line_dst_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edcstbliszonal',
            name='second_line_dst_results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_dst_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_dst_results_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
