# Generated by Django 4.2.20 on 2026-02-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0029_edcstbliszonal_first_line_dst_performed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstbliszonal',
            name='pretomanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tblis_laboratory_pretomanid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='pretomanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_laboratory_pretomanid_phenotypic_dst', to='options.phenotypicdstresults'),
        ),
    ]
