# Generated by Django 4.2.20 on 2026-02-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0030_edcstbliszonal_pretomanid_zonallaboratory_pretomanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonallaboratory',
            name='first_line_dst_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_first_line_dst_performed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='zonallaboratory',
            name='second_line_dst_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_second_line_dst_performed', to='options.yesno'),
        ),
    ]
