# Generated by Django 4.2.20 on 2026-02-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        ('nanopore', '0031_zonallaboratory_first_line_dst_performed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstbliszonal',
            name='first_line_dst_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tblis_first_line_dst_performed', to='options.yesno'),
        ),
        migrations.AddField(
            model_name='edcstbliszonal',
            name='second_line_dst_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tblis_second_line_dst_performed', to='options.yesno'),
        ),
        migrations.AlterField(
            model_name='edcstbliszonal',
            name='isolate_unique_lab_no',
            field=models.CharField(blank=True, help_text='Lab number, must be unique if present for isolate dst', max_length=100, null=True, unique=True),
        ),
    ]
