# Generated by Django 4.2.20 on 2026-02-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_nanoporesequencingdelayedreasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopore', '0032_edcstbliszonal_first_line_dst_performed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClinicLaboratory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('other_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('new_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('date_sample1_collected', models.DateField(blank=True, null=True)),
                ('date_sample1_received', models.DateField(blank=True, null=True)),
                ('sample1_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sample2_collected', models.DateField(blank=True, null=True)),
                ('date_sample2_received', models.DateField(blank=True, null=True)),
                ('sample2_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('afb_a_date', models.DateField(blank=True, null=True)),
                ('afb_b_date', models.DateField(blank=True, null=True)),
                ('xpert_date', models.DateField(blank=True, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('ct_value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ct_na', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('afb_a_results', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.afbmicroscopyresult')),
                ('afb_b_results', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.afbmicroscopyresult')),
                ('afb_microscopy_conducted', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.yesno')),
                ('appearance_sample1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.sampleappearance')),
                ('appearance_sample2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.sampleappearance')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.yesno')),
                ('number_received', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.samplenumber')),
                ('sample_reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.samplereason')),
                ('sample_received', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.yesno')),
                ('screening', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nanopore.screening')),
                ('technique_a', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.afbtechnique')),
                ('technique_b', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.afbtechnique')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('xpert_mtb', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.xpertmtb')),
                ('xpert_mtb_rif_conducted', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.yesno')),
                ('xpert_rif', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='options.xpertrif')),
            ],
            options={
                'verbose_name': 'historical clinic laboratory',
                'verbose_name_plural': 'historical clinic laboratorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
