# Generated by Django 4.2.20 on 2026-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0034_cliniclaboratory_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclaboratory',
            name='reason_for_change',
            field=models.TextField(blank=True, help_text='Reason for modifying a record; required if record is locked', null=True),
        ),
        migrations.AddField(
            model_name='historicalcliniclaboratory',
            name='reason_for_change',
            field=models.TextField(blank=True, help_text='Reason for modifying a record; required if record is locked', null=True),
        ),
    ]
