# Generated by Django 4.2.20 on 2026-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0035_cliniclaboratory_reason_for_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclaboratory',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcliniclaboratory',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
