# Generated by Django 4.2.20 on 2026-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0036_cliniclaboratory_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['site', 'pid'], name='nanopore_sc_site_id_77e34e_idx'),
        ),
    ]
