# Generated by Django 4.2.20 on 2026-06-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0037_screening_nanopore_sc_site_id_77e34e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdcsTblisMergeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_columns', models.IntegerField(default=0)),
                ('total_edcs_records', models.IntegerField(default=0)),
                ('total_tblis_rows', models.IntegerField(default=0)),
                ('matched_records', models.IntegerField(default=0)),
                ('missing_records', models.IntegerField(default=0)),
                ('edcs_not_in_tblis', models.IntegerField(default=0)),
                ('tblis_not_in_edcs', models.IntegerField(default=0)),
                ('tblis_date_from', models.CharField(blank=True, max_length=20, null=True)),
                ('tblis_date_to', models.CharField(blank=True, max_length=20, null=True)),
                ('total_mismatch_columns', models.IntegerField(default=0)),
                ('total_mismatch_records', models.IntegerField(default=0)),
                ('mismatch_by_field', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'EDCS–TBLIS Merge Summary',
                'verbose_name_plural': 'EDCS–TBLIS Merge Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
