# Generated by Django 4.2.20 on 2026-06-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0038_edcs_tblis_merge_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='test2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
