# Generated by Django 4.2.20 on 2026-06-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0039_screening_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='test3',
            field=models.CharField(blank=True, null=True),
        ),
    ]
