# Generated by Django 4.2.20 on 2026-06-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0040_screening_test3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='test3',
        ),
    ]
