# Generated by Django 4.2.20 on 2026-07-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopore', '0041_remove_screening_test2_remove_screening_test3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblisRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labno', models.CharField(db_index=True, help_text='Extracted from the raw TBLIS row', max_length=255)),
                ('raw_data', models.JSONField(default=dict, help_text='The entire raw row from the CSV')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_merged', models.BooleanField(default=False, help_text='True if this row was successfully merged into EdcsTblisZonal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
