# Generated by Django 4.2.20 on 2026-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0042_tblisrawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdcsNotInTblis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_lab_no', models.CharField(db_index=True, max_length=255)),
                ('pid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EdcsTblisMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labno', models.CharField(db_index=True, max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('edcs_value', models.TextField(blank=True, null=True)),
                ('tblis_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TblisNotInEdcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labno', models.CharField(db_index=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
