# Generated by Django 4.2.20 on 2026-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0043_edcsnotintblis_edcstblismismatch_tblisnotinedcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstblismismatch',
            name='pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
