# Generated by Django 4.2.20 on 2026-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0045_edcstblismergesummary_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_form_submissions', models.BooleanField(default=True, help_text="If unchecked, the 'Submit' button on all forms will be disabled.")),
                ('enable_new_screening', models.BooleanField(default=True, help_text="If unchecked, the 'New Screening' button will be hidden from the dashboard.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Control',
                'verbose_name_plural': 'System Controls',
            },
        ),
    ]
