# Generated by Django 4.2.20 on 2026-08-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopore', '0047_tblisuploadbatch_and_batch_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edcstbliszonal',
            options={'ordering': ['screening__site__district__region__zone__name', 'screening__site__name', 'screening__pid']},
        ),
        migrations.AlterModelOptions(
            name='tblisrawdata',
            options={'ordering': ['labno']},
        ),
        migrations.AlterModelOptions(
            name='zonallaboratory',
            options={'ordering': ['screening__site__district__region__zone__name', 'screening__site__name', 'screening__pid']},
        ),
    ]
