# Generated by Django 4.2.20 on 2025-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'enrolled_reason',
                'ordering': ['reason'],
            },
        ),
    ]
