# Generated by Django 4.2.20 on 2025-09-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrolledreason',
            table=None,
        ),
    ]
