# Generated by Django 4.2.20 on 2026-02-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitelevel',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='required',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
