# Generated by Django 4.2.20 on 2026-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_required_district_required_region_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitelevel',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitelevel',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='substudy2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='substudy4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
