# Generated by Django 4.2.20 on 2025-09-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.zone'),
        ),
    ]
