# Generated by Django 4.2.20 on 2026-02-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_substudy2_country_substudy4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='sitelevel',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='sitelevel',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='sitelevel',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='sitetype',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='sitetype',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='sitetype',
            old_name='substudy4',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='required',
            new_name='substudy2Target',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='substudy2',
            new_name='substudy4Target',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='substudy4',
            new_name='target',
        ),
    ]
