# Generated by Django 4.2.20 on 2025-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_region_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pid_prefix',
            field=models.CharField(default='', max_length=10),
        ),
    ]
