# Generated by Django 4.2.20 on 2025-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_site_pid_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='pid_prefix',
            field=models.CharField(default='', max_length=13),
        ),
    ]
