# Generated by Django 4.2.20 on 2026-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_country_substudy2target_and_more'),
        ('users', '0002_profile_description_profile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='locations.site'),
        ),
    ]
