# Generated by Django 4.2.20 on 2026-06-04 01:44

from django.db import migrations


def copy_site_to_sites(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        if profile.site:
            profile.sites.add(profile.site)

def reverse_copy_site_to_sites(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        if profile.sites.exists():
            profile.site = profile.sites.first()
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_sites'),
    ]

    operations = [
        migrations.RunPython(copy_site_to_sites, reverse_copy_site_to_sites),
    ]
