# Generated by Django 4.2.20 on 2026-06-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20260604_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='site',
        ),
    ]
