# Generated by Django 4.2.20 on 2026-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_country_substudy2target_and_more'),
        ('users', '0005_remove_profile_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='locations.zone'),
        ),
    ]
